 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/partner/orders", type: :request do
  # Partner::Order. As you add validations to Partner::Order, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Partner::Order.create! valid_attributes
      get partner_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order = Partner::Order.create! valid_attributes
      get partner_order_url(partner_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_partner_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      order = Partner::Order.create! valid_attributes
      get edit_partner_order_url(partner_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Partner::Order" do
        expect {
          post partner_orders_url, params: { partner_order: valid_attributes }
        }.to change(Partner::Order, :count).by(1)
      end

      it "redirects to the created partner_order" do
        post partner_orders_url, params: { partner_order: valid_attributes }
        expect(response).to redirect_to(partner_order_url(@partner_order))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Partner::Order" do
        expect {
          post partner_orders_url, params: { partner_order: invalid_attributes }
        }.to change(Partner::Order, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post partner_orders_url, params: { partner_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested partner_order" do
        order = Partner::Order.create! valid_attributes
        patch partner_order_url(partner_order), params: { partner_order: new_attributes }
        order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the partner_order" do
        order = Partner::Order.create! valid_attributes
        patch partner_order_url(partner_order), params: { partner_order: new_attributes }
        order.reload
        expect(response).to redirect_to(partner_order_url(order))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        order = Partner::Order.create! valid_attributes
        patch partner_order_url(partner_order), params: { partner_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested partner_order" do
      order = Partner::Order.create! valid_attributes
      expect {
        delete partner_order_url(partner_order)
      }.to change(Partner::Order, :count).by(-1)
    end

    it "redirects to the partner_orders list" do
      order = Partner::Order.create! valid_attributes
      delete partner_order_url(partner_order)
      expect(response).to redirect_to(partner_orders_url)
    end
  end
end
