 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/consumer/shops", type: :request do
  # Consumer::Shop. As you add validations to Consumer::Shop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Consumer::Shop.create! valid_attributes
      get consumer_shops_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shop = Consumer::Shop.create! valid_attributes
      get consumer_shop_url(consumer_shop)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_consumer_shop_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      shop = Consumer::Shop.create! valid_attributes
      get edit_consumer_shop_url(consumer_shop)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Consumer::Shop" do
        expect {
          post consumer_shops_url, params: { consumer_shop: valid_attributes }
        }.to change(Consumer::Shop, :count).by(1)
      end

      it "redirects to the created consumer_shop" do
        post consumer_shops_url, params: { consumer_shop: valid_attributes }
        expect(response).to redirect_to(consumer_shop_url(@consumer_shop))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Consumer::Shop" do
        expect {
          post consumer_shops_url, params: { consumer_shop: invalid_attributes }
        }.to change(Consumer::Shop, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post consumer_shops_url, params: { consumer_shop: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested consumer_shop" do
        shop = Consumer::Shop.create! valid_attributes
        patch consumer_shop_url(consumer_shop), params: { consumer_shop: new_attributes }
        shop.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the consumer_shop" do
        shop = Consumer::Shop.create! valid_attributes
        patch consumer_shop_url(consumer_shop), params: { consumer_shop: new_attributes }
        shop.reload
        expect(response).to redirect_to(consumer_shop_url(shop))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shop = Consumer::Shop.create! valid_attributes
        patch consumer_shop_url(consumer_shop), params: { consumer_shop: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested consumer_shop" do
      shop = Consumer::Shop.create! valid_attributes
      expect {
        delete consumer_shop_url(consumer_shop)
      }.to change(Consumer::Shop, :count).by(-1)
    end

    it "redirects to the consumer_shops list" do
      shop = Consumer::Shop.create! valid_attributes
      delete consumer_shop_url(consumer_shop)
      expect(response).to redirect_to(consumer_shops_url)
    end
  end
end
